openapi: "3.0.0"
info:
  title: XSS Test
  version: "1.0.0"
paths:
  /test:
    get:
      summary: test
      description: '<a href="javascript:alert(document.domain)">click me</a>'
      responses:
        "200":
          description: ok
